version: 0.2

phases:
  build:
    commands:
      - cd search-photos; zip -r ../search-photos.zip *; cd ..
      - cd index-photos; zip -r ../index-photos.zip *; cd ..


artifacts:
    files:
      - search-photos.zip
      - index-photos.zip
      - deployspec.yaml