version: 0.2

phases:
  pre_build:
    commands:
      - zip search-photos.zip lambda_function.py
  build:
    commands:
      - aws lambda update-function-code --function-name search-photos --region us-east-1 --zip-file fileb://search-photos.zip 
artifacts:
  files:
  - unpacked.yaml
  - packed.yaml